# General configuration for the application
name = "skeleton-app"
version = "0.0.1"
api_version = 1
environment = "development" # "development" or "production"

# Database configuration
[database]
    [database.elasticsearch]
    host = "127.0.0.1"
    port = 9200
    log = "trace"
    index = "veto"
    types = ["quotes"]
    
    [database.couchdb]
    host = "127.0.0.1"
    port = "5984"
    databases = ["test"]